os: linux
sudo: false
language: perl
perl:
- '5.26'
before_install:
- cpanm Carton
install:
- cd Conch; carton install --deployment
script:
- cd Conch; make test
cache:
  directories:
  - Conch/local
notifications:
  recipients:
  - sungo@joyent.com
  - lane.seppala@joyent.com
  email:
    on_success: change
    on_failure: always
